/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intelligentDatabank.business;

import com.intelligentDatabank.dao.UserDAO;
import com.intelligentDatabank.dao.impl.UserDAOImpl;
import com.intelligentDatabank.models.UserModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Akash
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LgginFrame
     */
    public LoginFrame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        setSize(width, height);
        setTitle("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginImageLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(47, 79, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intelligentDatabank/icons/Head_Brain.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, 290));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intelligentDatabank/icons/Hand_Brain.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 330, 320));

        backgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 760));

        loginImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intelligentDatabank/icons/Login_3.png"))); // NOI18N
        backgroundPanel.add(loginImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 250, 220));

        exitLabel.setBackground(new java.awt.Color(47, 79, 79));
        exitLabel.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("Exit");
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });
        backgroundPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 130, 40));

        loginLabel.setBackground(new java.awt.Color(47, 79, 79));
        loginLabel.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginLabel.setOpaque(true);
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLabelMouseExited(evt);
            }
        });
        backgroundPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 130, 40));

        passwordLabel.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(47, 79, 79));
        passwordLabel.setText("Password");
        backgroundPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 140, 30));

        userNameLabel.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(47, 79, 79));
        userNameLabel.setText("User Name");
        backgroundPanel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 140, 30));

        tfUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        backgroundPanel.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 390, 40));

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        backgroundPanel.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 390, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 79, 79));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        backgroundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 100, 50));

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseEntered
        loginLabel.setLocation(loginLabel.getX()+1, loginLabel.getY()+1);
    }//GEN-LAST:event_loginLabelMouseEntered

    private void loginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseExited
        loginLabel.setLocation(loginLabel.getX()-1, loginLabel.getY()-1);
    }//GEN-LAST:event_loginLabelMouseExited

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setLocation(exitLabel.getX()+1, exitLabel.getY()+1);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setLocation(exitLabel.getX()-1, exitLabel.getY()-1);
    }//GEN-LAST:event_exitLabelMouseExited

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        tfPassword.requestFocus();
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        UserModel userModel;
        UserDAO userDAO = new UserDAOImpl();
        if((tfUsername.getText().trim() != null) && (tfPassword.getText().trim() != null)) {
            userModel = userDAO.getUser(tfUsername.getText().trim(), tfPassword.getText().trim());
            if(userModel != null) {
                this.dispose();
                new MainFrame().setVisible(true);
            }else {
                JOptionPane.showMessageDialog(rootPane, "User is Not Valid");
            }
        }
    }//GEN-LAST:event_loginLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        UserModel userModel;
        UserDAO userDAO = new UserDAOImpl();
        if((tfUsername.getText().trim() != null) && (tfPassword.getText().trim() != null)) {
            userModel = userDAO.getUser(tfUsername.getText().trim(), tfPassword.getText().trim());
            if(userModel != null) {
                this.dispose();
                new MainFrame().setVisible(true);
            }else {
                JOptionPane.showMessageDialog(rootPane, "User is Not Valid");
            }
        }
    }//GEN-LAST:event_tfPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginImageLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
